#!/usr/bin/env node
/**
 * Builds sitemap.xml and robots.txt by walking the real prerendered output.
 *
 * Reading the actual `browser/` tree rather than a hand-maintained route list
 * means a route can never be in the app but missing from the sitemap, or the
 * other way around, and localized duplicates are picked up for free.
 */
import { readdir, writeFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const BROWSER = resolve(ROOT, 'dist/angular-project-generator/browser');
const SITE_URL = (process.env.SITE_URL ?? 'https://angular-project-generator.dev').replace(
  /\/+$/,
  '',
);

if (!existsSync(BROWSER)) {
  console.error('[sitemap] no prerendered output found. Run a build first.');
  process.exit(1);
}

async function collect(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...(await collect(full)));
    } else if (entry.name === 'index.html') {
      found.push(full);
    }
  }
  return found;
}

const files = await collect(BROWSER);
const routes = files
  .map((file) => {
    const rel = relative(BROWSER, file).split(sep).slice(0, -1).join('/');
    return rel ? `/${rel}` : '/';
  })
  // A prerendered 404 is a real file but must not be advertised.
  .filter((route) => !/\/404$/.test(route))
  .sort();

const stamps = new Map();
for (const file of files) {
  const info = await stat(file);
  stamps.set(file, info.mtime.toISOString().slice(0, 10));
}

const lastmod = [...stamps.values()].sort().at(-1) ?? new Date().toISOString().slice(0, 10);

const body = routes
  .map(
    (route) =>
      `  <url>\n    <loc>${SITE_URL}${route === '/' ? '/' : route}</loc>\n` +
      `    <lastmod>${lastmod}</lastmod>\n` +
      `    <changefreq>weekly</changefreq>\n` +
      `    <priority>${route === '/' ? '1.0' : '0.7'}</priority>\n  </url>`,
  )
  .join('\n');

await writeFile(
  join(BROWSER, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`,
  'utf8',
);

await writeFile(
  join(BROWSER, 'robots.txt'),
  `# Generated by scripts/generate-sitemap.mjs from the prerendered output.\nUser-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`,
  'utf8',
);

console.log(`[sitemap] ${routes.length} routes → sitemap.xml + robots.txt`);
